collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.6716792
  brandStrength: 1
  lightness: 0.4116541
  brandColors:
    - '#F2FEE8'
    - '#240725'
    - '#A5AEB5'
    - '#6A525F'
    - '#8B8891'
  rhythmicContrast: 0.7738096
typography_spectrum: 0.3132832
layout_spectrum: 0.5281955
name: Kåsøren
